### ISSUE TITLE
Use transients instead of options

### ISSUE THREAD

**Issue by allan23** [ericmann/wp-session-manager#36]
Right now the plugin adds and deletes sessions as options, which means that each user session will get stored in the wp_options table (two options per user session). If a site has a lot of traffic, this can make the wp_options table huge.

Instead of using options functions, it should be using transients. That way if an object cache (e.g. memcached) is available, then it can skip the wp_options table altogether.

**Comment by ericmann** [comment]
If object caching is not enabled, then transients are stored in the options table regardless. If object caching is enabled, but a different cache is used on each server to which the application is deployed, then we're back to the same situation we were with vanilla sessions.

**Comment by allan23** [comment]
Not sure I follow. Don't most setups use the same object cache server?

Let's say that object caching is enabled:
add_option() writes to the db, then stores into object cache.
set_transient() writes to object cache.

Let's also say that there are 500 visitors currently using a site. That means that 1,000 entries are added to the options table by using add_option(). Wouldn't it make sense to use set_transient() to write to object cache instead of a database?

Let me know if I'm way off on this.

**Comment by ericmann** [comment]
> Let's say that object caching is enabled:
add_option() writes to the db, then stores into object cache.
set_transient() writes to object cache.

Correct.

> Let's also say that there are 500 visitors currently using a site. That means that 1,000 entries are added to the options table by using add_option(). Wouldn't it make sense to use set_transient() to write to object cache instead of a database?

Yes and no. Yes it would make sense to write to an object cache. However, there is:
- No guarantee you'll hit the _same_ object cache on the next request. If you're directed to a different data center with a different cache pool, your session will disappear. This has been a significant issue with larger installs where each _web server_ has its own cache instance rather than a single, global cache instance for _all_ web servers
- No guarantee the cache will still be present on the next request. Some systems flush the entire cache when it gets filled and force a refresh. If sessions live only there, then they become highly unstable in those environments.

For now, Options (or perhaps Posts) are the safest place for persistent sessions for reliability. However, I'll be working on a refresh of this entire system to leverage a custom table instead to cut down on the amount of information stored.
