### ISSUE TITLE
PHP Warning:  Cannot modify header information

### ISSUE THREAD

**Issue by robertharm** [ericmann/wp-session-manager#40]
Hi Eric,

first thanks for your sharing wp-session-manager, I am using it in our WordPress mapping plugins Leaflet Maps Marker and Maps Marker Pro, supporting the throtteling of requests to geocoding engines.

I got a report from a user today about the following PHP error log
entry:

`PHP Warning:  Cannot modify header information - headers already sent by (output started at /wp-includes/functions.php:3673) in /wp-content/plugins/leaflet-maps-marker/inc/Stiphle/Storage/Session/class-wp-session.php on line 134`

Related code (line 134 = return setcookie...)

```
	protected function set_cookie() {
         	$secure = apply_filters('wp_session_cookie_secure', false);
         	$httponly = apply_filters('wp_session_cookie_httponly', false);
			return setcookie( WP_SESSION_COOKIE, $this->session_id . '||' . 
$this->expires . '||' . $this->exp_variant , $this->expires, COOKIEPATH, COOKIE_DOMAIN, $secure, $httponly );
	}
```

As I couldn´t really reproduce this issue, I wonder if you have an idea what causes this and how this warning could be avoided.
Any hint would be much appreciated!
best,

Robert

**Comment by ericmann** [comment]
This would be caused by any output (print statements, debug statements, `<header>` output, etc) before the `set_cookie()` function gets called. As `set_cookie()` is called inside the `WP_Session` constructor, this could be an instance of someone somewhere calling `new WP_Session` or `WP_Session::get_instance()` _after_ the theme (or another plugin) has already started producing output.

As the plugin itself ties the `get_instance()` call to the `plugins_loaded` action, my guess is that another plugin is loading _first_ and erroneously printing output to the page before all the other plugins have been able to load.

**Comment by robertharm** [comment]
thx for the info - will have a look if I can find that plugin. closing issue...
