### ISSUE TITLE
Question about updating sessions

### ISSUE THREAD

**Issue by tgelz** [ericmann/wp-session-manager#41]
Hello Eric,

thanks for your libraries. I know you're currently rewriting the code, but I was wondering if you could elaborate on why you chose to call delete_option() followed by add_option() when updating the sessions in class-wp-session.php, rather than just calling update_option()?

What am I missing here?

**Comment by ericmann** [comment]
Older version of WordPress (this plugin works back to 3.4.x) set autoload to true by default with `update_option` if the option was not already set. As a result, we need to use `add_option` at all times when creating data as we can't set the autoload flag to false on those older versions.

`add_option` also just chokes if the option already exists (instead of updating it), so attempting to delete it first is a safer way to do an in-place update.

Admittedly this isn't the _best_ code (some other systems use an `add_option` then, on failure reattempt with `update_option`). This approach would result in a second query only part of the time instead of all the time.

The rewrite will remove this necessity, though, so no worries there.

Also, I'll have an update out shortly to pull in some PRs and bump the released version both here and on WP.org.
