### ISSUE TITLE
Session Fails after if else

### ISSUE THREAD

**Issue by jiyanibharat303** [ericmann/wp-session-manager#44]
Hello on one single page -
I start from -
if(session_id() == '') session_start(); /*of course its in index.php I just written for the plugin stuff*/

$wp_session = WP_Session::get_instance();
then based on an parameter received in URL which will not be always there -
so for example 
--url--?test=1
if($_GET['test']){
$wp_session['test'] = 'testing';
} 

On second run  ---url--- no parameters 
and I want to check
if($wp_session['test']){
}else{
}
Get nothing here

**Comment by ericmann** [comment]
Where does this code live? The session needs to be started and, if you attempt to populate data too early in WP's lifecycle, things can fail. So, where are you populating the data (checking the `$_GET` parameter)? In the same request, can you grab this data back _out_ of the session?

**Comment by jiyanibharat303** [comment]
With all due respect to you - 
this thing 
if(session_id() == '') session_start(); is not working therefore I used the Plugin.
It mentions this will work like $_SESSION so if on first load it was set should it not return on next load or this $wp_session = WP_Session::get_instance(); just starts new all time

**Comment by ericmann** [comment]
If you're having troubles with `if(session_id() == '') session_start();` working, then I would suggest taking a look at _where_ that code is being invoked (which is why I asked where the code lives).

WP_Session is meant for use in systems where a traditional PHP session won't work because of load balancing (i.e. you have multiple servers handling requests, so storing session data in the filesystem of _one_ server won't work). If your site is running on a single server, you should use standard PHP sessions instead.

Again, though, let's debug _why_ this isn't working for you. Please answer the following:
- Where are you initializing the session? (Which file, which action, etc)
- Are you using any kind of front-end page cache?

**Comment by jiyanibharat303** [comment]
Hello Sir,
With ref to following link
https://stackoverflow.com/questions/1441240/wordpress-session-management

I have placed following code in wp-config.php
if (!session_id()) {
    session_start();
}

This code in theme's header.php at first line:
session_start();
and after that the following
$wp_session = WP_Session::get_instance(); code.

No not using any front-end page cache.

**Comment by ericmann** [comment]
I would suggest you re-try your test. There was a bug in an older version of the plugin that resulted in cached session data not reliably returning early in the plugin's execution. That's now been fixed and this issue should be resolved.
