### ISSUE TITLE
Doesn't work on Flywheel or Pantheon

### ISSUE THREAD

**Issue by pderksen** [ericmann/wp-session-manager#56]
I'm using WP Session Manager on a variety of hosts, but it doesn't work on Flywheel or Pantheon sites in my testing.

If you inspect the cookies, the `_wp_session` value does not stay the same between page refreshes or redirects.

I'm still investigating but wanted to start a thread on this in case anyone else has any insight or thoughts.

**Comment by ericmann** [comment]
I can't speak for Flywheel, but when it comes to managed hosts there's usually an explicit whitelist of cookies that are allowed to bust the cache. By default, pages will be served through a cache (i.e. Varnish) and won't respect the use of PHP-side sessions for persistent state. When using sessions (or any session plugin) you'll have to work with the host to allow things through.

For Pantheon specifically, though, I'd recommend using https://github.com/pantheon-systems/wp-native-php-sessions instead.It's thoroughly tested with their platform. (Also, since they maintain it, they'll be the best people to support it on their own system.)

**Comment by pderksen** [comment]
@ericmann I looked into Pantheon's plugin, but it didn't work for me to integrate it into my plugin, [WP Simple Pay](https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe/) as easily as it was to integrate WP Session Manager.

I'd prefer to NOT require every user/customer of mine to install a separate plugin handling sessions to make it work, let alone them having to pick yours or a separate host-specific one like Pantheon's.

In any case, I've used previous versions of WP Session Manager within my Lite & Pro plugins, just like EDD, Give and Ninja Forms (among others) have. Then I tried Pantheon's. Now I'm back to yours, but more current. [Here's my own PR](https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe/issues/38) on the issue.

Thanks!

**Comment by ericmann** [comment]
Hmm ...

I'm working on a 3.x release that will be shifting to using PHP _native_ sessions a bit more regularly. This means the default `PHPSESSIONID` cookie instead of a custom one for the plugin. That might be a bit more useful for you.

I'm fairly confident the Pantheon conflict is due to how they handle requests passing through the cache. Do you have a sense for where things are breaking down with Flywheel so I can investigate a fix?

**Comment by pderksen** [comment]
That sounds like the right direction for WPSM 3.x using PHP native sessions.

Here's a couple screencasts showing the `_wp_session` cookie value in Chrome dev tools after page refreshes.

This is running a clean WP 4.9.1 site with only WP Session Manager 2.0.2 along with a custom plugin that simply sets & reads one session var for testing.

The first one is WP Engine, and the `_wp_session` cookie value stays as is as expected. This is the case for most other hosts as well.

You'll see on Pantheon & Flywheel it gets reset every time.

- WP Engine: https://screencast.com/t/JiKshBuh
- Pantheon: https://screencast.com/t/wC116zL6
- Flywheel: https://screencast.com/t/1YpGfV8P

Hope that helps!

**Comment by pderksen** [comment]
@ericmann I got our implementation of WP Session Manager 2.0.2 working within WP Simple Pay Lite & Pro for all hosts _except_ Pantheon. Flywheel seems to work fine now.

So instead, we made a special check for their WP Native PHP Sessions plugin and forced use of PHP sessions if found. See https://github.com/pantheon-systems/wp-native-php-sessions/issues/81#issuecomment-355661409

We also added a constant to allow forcing of use of PHP Sessions in wp-config.php if the site owner desires.

**Comment by danielbachhuber** [comment]
> I'm fairly confident the Pantheon conflict is due to how they handle requests passing through the cache.

This is correct. The standard PHP session cookie can bypass the cache but other random cookies cannot.

**Comment by ericmann** [comment]
> We also added a constant to allow forcing of use of PHP Sessions in wp-config.php if the site owner desires.

Awesome. For the record, the next major version of this plugin will be using native sessions instead of a custom cookie, so once that's out you should be golden without a custom workaround.
