### ISSUE TITLE
session->reset seems to succeed, but data returns to container array

### ISSUE THREAD

**Issue by MikeiLL** [ericmann/wp-session-manager#68]
Hi and thank you for your visionary work, man.

I'm using version 2.0.2 kind of like EDD does within a [plugin](https://github.com/MikeiLL/mz-mindbody-api/tree/re-up).

When I run `session->reset()`, the `container` array is cleared, but then seems to still contain the previous data in memory, as well as in the database, with the same `session_id`.

I even tried running `session->write_data()`, to my "logout" routine, which it looks like should either destroy the session or overwrite the `session_value` in the database, but doesn't.

If I run `delete_session()` the database entry is cleared, but the `session` seems to persist in memory (minus the container data). Is this because the session was just started and `expires` and `exp_variant` are configured to store the data via a $_COOKIE?

I saw [reference](https://github.com/ericmann/wp-session-manager/issues/25) to documentation in the issues, but haven't been successful finding it so apologies if this is a spammy thread.

Happy Summer and thanks.

**Comment by ericmann** [comment]
Unfortunately, you're in a sticky situation that's difficult to clean up. Newer versions of the plugin present a `session_destroy()` function from native PHP that will both purge in-memory and in-database data. If you can upgrade, please do.

If you _can't_ upgrade, here's a workaround:
- Run `$session->reset()` like you're already doing
- Immediately add a dummy value to the session
- _Now_ call `$session->write_data()`

Your previous setup was clearing the container array, but that was it. And calling `::write_data()` didn't help because the container array didn't see itself as "dirty" and needing a rewrite. Adding any new data (including a dummy value) will trick the container into thinking it needs to resync with the database, which will overwrite the database entry.

All of these issues are why I rolled the version in 3.X and later to leverage PHP's native session management routines.

**Comment by MikeiLL** [comment]
Hey thanks for this, Eric. Just finally seeing it now. I am not finding a `session_destroy()` method in the `v3.0`, and see that we are on to `v4.x`.

Since the new version has Sessionz as a dependency, I think this will be the catalyst to start using Composer within my plugin to manage dependencies. I'm not sure how that works yet, or if it's possible to have multiple autoload functions within the same application.

So in the meantime, is this what you mean as a workaround:

   ```
    public function clear() {
        if ( $this->use_php_sessions ) {
            unset( $_SESSION[ $this->prefix ] );
        } else {
            $this->session->reset();
            $this->set( 'cleanup_hack', '1');
            $this->session->write_data();
            WP_Session\WP_Session_Utils::delete_session($this->get_id());
        }
    }
```
Thanks much, Eric Mann.

**Comment by MikeiLL** [comment]
The kind folks at TimerSys are using a slightly older (php5.6 compliant) version of the plugin in one of their plugins and shared this example of including WP-Session-Manager as well as it's dependency, Sessionz via composer:

[in this repo](https://github.com/timersys/geotargetingwp-plugin/blob/3.0.2.2/composer.json)
