### ISSUE TITLE
session_id increments on each page load

### ISSUE THREAD

**Issue by sandrodz** [ericmann/wp-session-manager#71]
Is there any particular reason to increment session_id on each page load?

<img width="560" alt="screen shot 2018-12-26 at 8 09 22 pm" src="https://user-images.githubusercontent.com/8479569/50450905-43b9f100-094a-11e9-8889-a940a352ef05.png">

I'm doing page refresh on two test sessions, and each time number goes up.

**Comment by ericmann** [comment]
To clarify, the ID is incrementing, but the session key is staying static? Or are you seeing something else?

(No, there's no particular reason to do that ... you might have found a bug.)

**Comment by ericmann** [comment]
Digging deeper into this, the incrementing ID is a result of using a `REPLACE` query in MySQL when we write data back into the session. The _key_ doesn't change, but the ID increments automatically to keep track fo the fact that the row itself has changed.

This isn't a bug per se, but a quirk of the SQL interface. We could likely get rid of the ID column entirely in a future release if it's causing hiccups for you.

**Comment by sandrodz** [comment]
It is not causing hiccups, just seemed odd.
Neither `session_value` nor `session_key` have changed so it is unexpected for `session_id` to change.

> track fo the fact that the row itself has changed

But no row value has changed.

Also how will this scale? Counting page views this way, you can reach bigINT limits pretty fast on busy websites.

**Comment by ericmann** [comment]
Also how will this scale? Counting page views this way, you can reach bigINT limits pretty fast on busy websites.

It wasn't an intentional feature to count pageviews. If there's an auto-incrementing ID on a table that you execute a `REPLACE` on, this is just a side effect of the way MySQL works under the hood.I'll look into eliminating this extraneous ID in the next version regardless.

**Comment by sandrodz** [comment]
@ericmann  another thing I've noticed, on each page refresh, `session_expiry` also goes up.  So session never expires. Is this normal?

**Comment by ericmann** [comment]
That is intentional. A session stays active so long as the visitor is actively using the site and auto updates the expiration on page load to keep the session fresh. This is expected behavior.On Dec 29, 2018 6:33 AM, Sandro Dzneladze <notifications@github.com> wrote:@ericmann  another thing I've noticed, on each page refresh, session_expiry also goes up.  So session never expires. Is this normal?

**Comment by sandrodz** [comment]
@ericmann last question and I will leave you to a new year celebrations ^_^ in my case it seems sessions do not auto expire at all. Do I need to setup a cron to run session cleanup?

**Comment by ericmann** [comment]
Cleanup from the database should be handled directly by PHP, but that appears to be malfunctioning at the moment. I've opened #77 to address it in the next release.
