### ISSUE TITLE
wp cli errors with plugin activated

### ISSUE THREAD

**Issue by sandrodz** [ericmann/wp-session-manager#79]
When plugin is activated wpcli errors out.

<img width="897" alt="screen shot 2019-02-09 at 1 08 22 am" src="https://user-images.githubusercontent.com/8479569/52525963-1ee7c600-2ccb-11e9-8d4f-da5035fd2021.png">

Could be my wordplate setup with docker, will dig dipper in a week.

**Comment by ericmann** [comment]
This error turns out to be because sessions themselves are disabled. `SessionHandlerInterface` is a core feature of PHP itself, but if sessions are disabled then it won't exist.

I have a new change I'm adding with 4.1.1 that makes sure sessions are enabled before bootstrapping anything, but on your system it looks like sessions won't work at all (at least not in the CLI version of PHP ... maybe you have FPM configured differently).

**Comment by ericmann** [comment]
Fixed with 4.1.1

**Comment by sandrodz** [comment]
@ericmann yes my wp-cli lives in a container, https://github.com/wearede/DevCeption/blob/master/provisioning/roles/php-tools/files/wp it is possible sessions are disabled in this one. But it should not fail with a fatal error. Thanks for adding function exists checks :)
